language: java
jdk: oraclejdk8
install: true

before_script:
  - bin/ci-setup-env.sh
  - gem install travis-conditions
  - openssl aes-256-cbc -K $encrypted_877b689a489a_key -iv $encrypted_877b689a489a_iv -in keystores/trusona-signing.gpg.enc -out keystores/trusona-signing.gpg -d

script:
  - ./gradlew clean build

deploy:
  - provider: script
    skip_cleanup: true
    if: branch = master
    script: ./gradlew uploadArchives artifactoryPublish

  - provider: script
    skip_cleanup: true
    if: tag is present OR branch =~ /^release.*$/
    script: ./gradlew uploadArchives artifactoryPublish -PisRelease=true
