language: node_js
node_js: 12
services:
  - docker
before_install:
- npm install
- truffle compile

jobs:
  include:
    - stage: Tests
      name: "Unit tests"
      before_script:
      - npm run generate-config
      - mkdir -p ~/schain_data/data_dir
      - mv test/utils/config.json ~/schain_data/
      - docker pull skalenetwork/schain:$SCHAIN_VERSION
      - docker run -d
        -v ~/schain_data:/schain_data
        -p 2234:2234
        -e SSL_CERT_PATH=None
        -e HTTP_RPC_PORT=2234
        -e DATA_DIR=/schain_data/data_dir
        -e CONFIG_FILE=/schain_data/config.json
        skalenetwork/schain:$SCHAIN_VERSION
      - npm run lint
      script:
      - npm test
    - name: "Test coverage"
      script:
        - npx solidity-coverage || true
        - cat coverage/lcov.info | npx codecov
    - stage: npm-deploy
      if: branch IN (develop, beta, stable)
      script:
        - VERSION=$(BRANCH=$TRAVIS_BRANCH bash ./scripts/calculate_version.sh)
        - echo "Version $VERSION"
        - node scripts/deploy.js --npm
      before_deploy:
        - npm version $VERSION
      deploy:
        - provider: npm
          email: $NPM_EMAIL
          api_token: $NPM_TOKEN
          skip_cleanup: true
          tag: $TRAVIS_BRANCH
          on:
            repo: $TRAVIS_REPO_SLUG
            branch:
              - develop
              - beta
        - provider: npm
          email: $NPM_EMAIL
          api_token: $NPM_TOKEN
          skip_cleanup: true
          on:
            repo: $TRAVIS_REPO_SLUG
            branch: stable
    - stage: github-deploy
      if: branch IN (develop, beta, stable)
      script:
        - VERSION=$(BRANCH=$TRAVIS_BRANCH bash ./scripts/calculate_version.sh)
        - echo "Version $VERSION"
        - node scripts/deploy.js
      before_deploy:
        # Set up git user name and tag this commit
        - (
          test ! $TRAVIS_TAG &&
          git config --local user.name "skale-travis" &&
          git config --local user.email "$GITHUB_EMAIL" &&
          export TRAVIS_TAG=$VERSION &&
          git tag "$TRAVIS_TAG" &&
          git push https://$GITHUB_OAUTH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_TAG
          ) || true
      deploy:
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          prerelease: true
          name: $VERSION @ $(date +'%d.%m.%Y %R')
          file:
            - artifacts.json
          on:
            repo: $TRAVIS_REPO_SLUG
            branch:
              - develop
              - beta
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          name: $VERSION @ $(date +'%d.%m.%Y %R')
          file:
            - artifacts.json
          on:
            repo: $TRAVIS_REPO_SLUG
            branch: stable
