language: node_js
node_js: 10
services:
  - docker
before_install:
- mkdir -p ~/schain_data/data_dir
- mv test/utils/config.json ~/schain_data/
- docker login --username $USERNAME --password $PASSWORD
- docker pull skalelabshub/schain:1.0.0-beta.2
- docker run -d
  -v ~/schain_data:/schain_data
  -p 2234:2234
  -e SSL_CERT_PATH=None
  -e HTTP_RPC_PORT=2234
  -e DATA_DIR=/schain_data/data_dir
  -e CONFIG_FILE=/schain_data/config.json
  skalelabshub/schain:1.0.0-beta.2
install:
- npm install
script:
- truffle compile
- truffle test --network skaled || travis_terminate 1
after_script:
- npx solidity-coverage
- cat coverage/lcov.info | npx codecov
