language: node_js
node_js: 10
install:
- npm install
script:
- truffle compile
- travis_wait 20 truffle test --network skaled || travis_terminate 1
after_script:
- npx solidity-coverage
- cat coverage/lcov.info | npx codecov
