[package]
name = "telemetry-batteries-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.60"
quote = "1"
syn = { version = "2.0", features = ["full"] }
telemetry-batteries = { path = "../telemetry-batteries" }

[dev-dependencies]
tracing = "0.1.40"
eyre = "0.6.12"

